# generated by datamodel-codegen:
#   filename:  genai-ny.json
#   timestamp: 2025-12-06T18:13:57+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel, ConfigDict


class Coordinate(BaseModel):
    model_config = ConfigDict(extra="ignore")

    longitude: Optional[float] = None
    latitude: Optional[float] = None


class Calendar(BaseModel):
    model_config = ConfigDict(extra="ignore")

    access_level: Optional[str] = None
    api_id: Optional[str] = None
    avatar_url: Optional[str] = None
    coordinate: Optional[Coordinate] = None
    cover_image_url: Optional[str] = None
    description_short: Optional[str] = None
    event_submission_restriction: Optional[str] = None
    geo_city: Optional[str] = None
    geo_country: Optional[str] = None
    geo_region: Optional[str] = None
    google_measurement_id: Optional[Any] = None
    instagram_handle: Optional[str] = None
    is_blocked: Optional[bool] = None
    launch_status: Optional[str] = None
    linkedin_handle: Optional[str] = None
    luma_plus_active: Optional[bool] = None
    meta_pixel_id: Optional[Any] = None
    name: Optional[str] = None
    personal_user_api_id: Optional[str] = None
    refund_policy: Optional[Any] = None
    show_subscriber_count: Optional[bool] = None
    slug: Optional[str] = None
    social_image_url: Optional[str] = None
    stripe_account_id: Optional[str] = None
    tax_config: Optional[Any] = None
    tiktok_handle: Optional[str] = None
    timezone: Optional[str] = None
    tint_color: Optional[str] = None
    track_meta_ads_from_luma: Optional[bool] = None
    twitter_handle: Optional[str] = None
    verified_at: Optional[str] = None
    website: Optional[str] = None
    youtube_handle: Optional[str] = None
    is_personal: Optional[bool] = None


class VirtualInfo(BaseModel):
    model_config = ConfigDict(extra="ignore")

    has_access: Optional[bool] = None


class GeoAddressInfo(BaseModel):
    model_config = ConfigDict(extra="ignore")

    mode: Optional[str] = None
    city_state: Optional[str] = None
    sublocality: Optional[str] = None
    city: Optional[str] = None
    type: Optional[str] = None
    region: Optional[str] = None
    address: Optional[str] = None
    country: Optional[str] = None
    place_id: Optional[str] = None
    description: Optional[str] = None
    country_code: Optional[str] = None
    full_address: Optional[str] = None
    apple_maps_place_id: Optional[str] = None


class Coordinate1(BaseModel):
    model_config = ConfigDict(extra="ignore")

    latitude: Optional[float] = None
    longitude: Optional[float] = None


class Event(BaseModel):
    model_config = ConfigDict(extra="ignore")

    api_id: Optional[str] = None
    calendar_api_id: Optional[str] = None
    cover_url: Optional[str] = None
    end_at: Optional[str] = None
    event_type: Optional[str] = None
    hide_rsvp: Optional[bool] = None
    location_type: Optional[str] = None
    name: Optional[str] = None
    one_to_one: Optional[bool] = None
    recurrence_id: Optional[Any] = None
    show_guest_list: Optional[bool] = None
    start_at: Optional[str] = None
    timezone: Optional[str] = None
    url: Optional[str] = None
    user_api_id: Optional[str] = None
    visibility: Optional[str] = None
    waitlist_enabled: Optional[bool] = None
    virtual_info: Optional[VirtualInfo] = None
    geo_address_info: Optional[GeoAddressInfo] = None
    geo_address_visibility: Optional[str] = None
    coordinate: Optional[Coordinate1] = None


class CoverImage(BaseModel):
    model_config = ConfigDict(extra="ignore")

    vibrant_color: Optional[Any] = None
    colors: Optional[List[str]] = None


class Coordinate2(BaseModel):
    model_config = ConfigDict(extra="ignore")

    longitude: Optional[float] = None
    latitude: Optional[float] = None


class Attrs(BaseModel):
    model_config = ConfigDict(extra="ignore")

    href: Optional[str] = None


class Mark(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: Optional[str] = None
    attrs: Optional[Attrs] = None


class ContentItem1(BaseModel):
    model_config = ConfigDict(extra="ignore")

    text: Optional[str] = None
    type: Optional[str] = None
    marks: Optional[List[Mark]] = None


class ContentItem(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: Optional[str] = None
    content: Optional[List[ContentItem1]] = None


class RefundPolicy(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: Optional[str] = None
    content: Optional[List[ContentItem]] = None


class Calendar1(BaseModel):
    model_config = ConfigDict(extra="ignore")

    access_level: Optional[str] = None
    api_id: Optional[str] = None
    avatar_url: Optional[str] = None
    coordinate: Optional[Coordinate2] = None
    cover_image_url: Optional[str] = None
    description_short: Optional[str] = None
    event_submission_restriction: Optional[str] = None
    geo_city: Optional[str] = None
    geo_country: Optional[str] = None
    geo_region: Optional[str] = None
    google_measurement_id: Optional[Any] = None
    instagram_handle: Optional[str] = None
    is_blocked: Optional[bool] = None
    launch_status: Optional[str] = None
    linkedin_handle: Optional[str] = None
    luma_plus_active: Optional[bool] = None
    meta_pixel_id: Optional[Any] = None
    name: Optional[str] = None
    personal_user_api_id: Optional[str] = None
    refund_policy: Optional[Any] = None
    show_subscriber_count: Optional[bool] = None
    slug: Optional[str] = None
    social_image_url: Optional[str] = None
    stripe_account_id: Optional[str] = None
    tax_config: Optional[Any] = None
    tiktok_handle: Optional[str] = None
    timezone: Optional[str] = None
    tint_color: Optional[str] = None
    track_meta_ads_from_luma: Optional[bool] = None
    twitter_handle: Optional[str] = None
    verified_at: Optional[str] = None
    website: Optional[str] = None
    youtube_handle: Optional[str] = None
    is_personal: Optional[bool] = None


class Host(BaseModel):
    model_config = ConfigDict(extra="ignore")

    name: Optional[str] = None
    api_id: Optional[str] = None
    website: Optional[str] = None
    timezone: Optional[str] = None
    username: Optional[str] = None
    bio_short: Optional[str] = None
    avatar_url: Optional[str] = None
    is_verified: Optional[bool] = None
    tiktok_handle: Optional[str] = None
    last_online_at: Optional[str] = None
    twitter_handle: Optional[str] = None
    youtube_handle: Optional[str] = None
    linkedin_handle: Optional[str] = None
    instagram_handle: Optional[str] = None


class Price(BaseModel):
    model_config = ConfigDict(extra="ignore")

    cents: Optional[int] = None
    currency: Optional[str] = None
    is_flexible: Optional[bool] = None


class CurrencyInfo(BaseModel):
    model_config = ConfigDict(extra="ignore")

    currency: Optional[str] = None
    decimals: Optional[int] = None


class TicketInfo(BaseModel):
    model_config = ConfigDict(extra="ignore")

    price: Optional[Price] = None
    is_free: Optional[bool] = None
    max_price: Optional[Any] = None
    is_sold_out: Optional[bool] = None
    spots_remaining: Optional[int] = None
    is_near_capacity: Optional[bool] = None
    require_approval: Optional[bool] = None
    currency_info: Optional[CurrencyInfo] = None


class FeaturedGuest(BaseModel):
    model_config = ConfigDict(extra="ignore")

    api_id: Optional[str] = None
    avatar_url: Optional[str] = None
    bio_short: Optional[str] = None
    instagram_handle: Optional[str] = None
    is_verified: Optional[bool] = None
    last_online_at: Optional[str] = None
    linkedin_handle: Optional[str] = None
    name: Optional[str] = None
    tiktok_handle: Optional[str] = None
    twitter_handle: Optional[str] = None
    username: Optional[str] = None
    website: Optional[str] = None
    youtube_handle: Optional[str] = None


class Tag(BaseModel):
    model_config = ConfigDict(extra="ignore")

    api_id: Optional[str] = None
    name: Optional[str] = None
    color: Optional[str] = None


class FeaturedItem(BaseModel):
    model_config = ConfigDict(extra="ignore")

    api_id: Optional[str] = None
    event: Optional[Event] = None
    cover_image: Optional[CoverImage] = None
    calendar: Optional[Calendar1] = None
    start_at: Optional[str] = None
    hosts: Optional[List[Host]] = None
    guest_count: Optional[int] = None
    ticket_count: Optional[int] = None
    ticket_info: Optional[TicketInfo] = None
    featured_guests: Optional[List[FeaturedGuest]] = None
    role: Optional[Any] = None
    waitlist_active: Optional[bool] = None
    calendar_api_id: Optional[str] = None
    is_manager: Optional[bool] = None
    platform: Optional[str] = None
    status: Optional[str] = None
    submitted_by_user_api_id: Optional[str] = None
    tags: Optional[List[Tag]] = None


class Tag1(BaseModel):
    model_config = ConfigDict(extra="ignore")

    api_id: Optional[str] = None
    name: Optional[str] = None
    color: Optional[str] = None
    upcoming_event_count: Optional[int] = None


class AccessInfo(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: Optional[str] = None
    require_approval: Optional[bool] = None
    currency: Optional[str] = None
    amount_yearly: Optional[int] = None
    amount_monthly: Optional[int] = None
    stripe_account_id: Optional[str] = None
    stripe_product_id: Optional[str] = None
    stripe_yearly_price_id: Optional[str] = None
    stripe_monthly_price_id: Optional[str] = None


class RegistrationQuestion(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: Optional[str] = None
    label: Optional[str] = None
    options: Optional[List[str]] = None
    required: Optional[bool] = None
    question_type: Optional[str] = None
    job_title_label: Optional[str] = None
    collect_job_title: Optional[bool] = None


class MembershipTier(BaseModel):
    model_config = ConfigDict(extra="ignore")

    api_id: Optional[str] = None
    access_info: Optional[AccessInfo] = None
    description: Optional[str] = None
    registration_questions: Optional[List[RegistrationQuestion]] = None
    calendar_api_id: Optional[str] = None
    tint_color: Optional[str] = None
    name: Optional[str] = None


class Model(BaseModel):
    model_config = ConfigDict(extra="ignore")

    calendar: Optional[Calendar] = None
    featured_items: Optional[List[FeaturedItem]] = None
    has_upcoming_events: Optional[bool] = None
    has_access: Optional[bool] = None
    is_admin: Optional[bool] = None
    calendar_member: Optional[Any] = None
    is_subscriber: Optional[bool] = None
    tags: Optional[List[Tag1]] = None
    event_start_ats: Optional[List[str]] = None
    membership_tiers: Optional[List[MembershipTier]] = None
    subscriber_count: Optional[Any] = None
    categories: Optional[List[Any]] = None
    membership_info: Optional[Any] = None
    can_subscribe: Optional[bool] = None
